#!/bin/sh

. /etc/rc.subr

name="ftp_watchd"
desc="Pure-ftpd watcher daemon"
rcvar="ftp_watchd_enable"

start_precmd="ftp_watchd_prestart"
stop_postcmd="ftp_watchd_stop"

ftp_watchd_prestart() {
	cp /usr/local/bin/uploadscript.sh /tmp/fws.sh
	#echo '#!/bin/sh' > /tmp/fws.sh
	#sed -n 's/ftp_watchd_command="\(.*\)"/\1/gp' /etc/rc.conf >> /tmp/fws.sh
	chmod +x /tmp/fws.sh
}
ftp_watchd_stop() {
	pid_num=$(cat /var/run/pure-uploadscript.pid)
	echo "kill: $pid_num"
}
command="/usr/local/sbin/pure-uploadscript"
command_args="-B -r /tmp/fws.sh"

load_rc_config $name
run_rc_command "$1"
